website/demos/urls.py
from django.urls import path
from demos.feeds import LatestEntriesFeed, LatestEntriesWithImagesFeed
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from demos.models import Game, Magazine, Source

from . import views
app_name = "demos"

gamelist = {
    "queryset": Game.objects.all(),
    "date_field": "added"
}

sourcelist = {
    "queryset": Source.objects.all(),
    "date_field": "added"
}

magazinelist = {
    "queryset": Magazine.objects.all()
}

urlpatterns = [
    path("", views.home, name="home"),
    path("games/", views.GameListView.as_view(), kwargs={ "order": "game" }, name="games"),
    path("nn/games/", views.GameListView.as_view(), kwargs={ "order": "game", "nonav": "true" }, name="games_nn"),
    path("playable/", views.GameListView.as_view(), kwargs={ "order": "game", "constraint": "playable" }, name="playable"),
    path("play/<slug:slug>/", views.play, name="play"),
    path("<slug:slug>", views.DemoView.as_view(), name="demo"),
    path("download/<slug:slug>/", views.download, { "dl": 1 }, name="download"),
    path("download/2/<slug:slug>/", views.download, { "dl": 2 }, name="download/2"),
    path("download/3/<slug:slug>/", views.download, { "dl": 3 }, name="download/3"),
    path("explore/<slug:slug>/", views.explore, { "disc": 1, "osx": False }, name="explore"),
    path("explore/osx/<slug:slug>/", views.explore, { "disc": 1, "osx": True }, name="explore/osx"),
    path("explore/2/<slug:slug>/", views.explore, { "disc": 2, "osx": False }, name="explore/2"),
    path("explore/2/osx/<slug:slug>/", views.explore, { "disc": 2, "osx": True  }, name="explore/2/osx"),
    path("explore/3/<slug:slug>/", views.explore, { "disc": 3, "osx": False }, name="explore/3"),
    path("explore/3/osx/<slug:slug>/", views.explore, { "disc": 3, "osx": True  }, name="explore/3/osx"),
    path("explore/4/<slug:slug>/", views.explore, { "disc": 4, "osx": False }, name="explore/4"),
    path("explore/4/osx/<slug:slug>/", views.explore, { "disc": 4, "osx": True  }, name="explore/4/osx"),
    path("discs/", views.MagazineListView.as_view(), name="sources"),
    path("nn/discs/", views.MagazineListView.as_view(), kwargs={ "nonav": "true" }, name="sources_nn"),
    path("disc/<slug:slug>/", views.SourceView.as_view(), name="source"),
    path("about/", views.about, name="about"),
    path("rss/", LatestEntriesFeed(), name="rss"),
    path("rss/withimages/", LatestEntriesWithImagesFeed(), name="rsswithimages"),
    path("sitemap.xml", sitemap, { "sitemaps": { 
                                    "games": GenericSitemap(gamelist, protocol="https"),
                                    "magazines": GenericSitemap(magazinelist, protocol="https"),
                                    "discs": GenericSitemap(sourcelist, protocol="https")
                                    }
                                   }, name="django.contrib.sitemaps.views.sitemap"),
    path("magazine/<slug:slug>/", views.MagazineView.as_view(), name="magazine"),
    path("classicmacdemos.css", views.css, name="css"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include("demos.urls")),
    path('admin/', admin.site.urls),
]

website/demos/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Min, Max, Count, Q

import django, math, boto3

def convert_size(size_bytes):
   if size_bytes == 0:
       return "0B"
   size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
   i = int(math.floor(math.log(size_bytes, 1024)))
   p = math.pow(1024, i)
   s = round(size_bytes / p, 2)
   return "%s %s" % (s, size_name[i])

class Months(models.IntegerChoices):
    JAN = 1
    FEB = 2
    MAR = 3
    APR = 4
    MAY = 5
    JUN = 6
    JUL = 7
    AUG = 8
    SEPT = 9
    OCT = 10
    NOV = 11
    DEC = 12
    Holiday = 13

class VirtualMachine(models.Model):
    description = models.CharField("Description", max_length=50, blank=False)
    website_description = models.CharField("Website description", max_length=50, blank=True)
    machine     = models.CharField("Machine configuration", max_length=100, blank=False)
    disk        = models.CharField("Disk name", max_length=50, blank=True)
    def __str__(self): return self.description

class Language(models.Model):
    name = models.CharField("Name", max_length=50, blank=False)
    iso  = models.CharField("ISO 639-1 Code", max_length=2, blank=False)
    icon = models.CharField("Icon", max_length=8, blank=False)
    def __str__(self): return self.name

class Country (models.Model):
    name = models.CharField("Name", max_length=50, blank=False)
    iso  = models.CharField("ISO 3166 Code", max_length=2, blank=False)
    icon = models.CharField("Icon", max_length=8, blank=False)
    display_order = models.IntegerField("Display order", blank=False, default=0)
    def __str__(self): return self.name

class Game(models.Model):
    s3 = boto3.client('s3')
    game = models.CharField("Game", max_length=200)
    aka  = models.CharField("aka", max_length=200, blank=True)
    contributor = models.CharField("Contributed by", max_length=200, blank=True)
    contributor_url = models.URLField("Contributor URL", blank=True)
    year = models.IntegerField("Published", default=2000)
    languages = models.ManyToManyField(Language, blank=True)
    filename = models.CharField("Download file name", max_length=100)
    filename_68k = models.CharField("Download 2 File name", max_length=100, blank=True)
    filename_3 = models.CharField("Download 3 File name", max_length=100, blank=True)
    readme_txt = models.BooleanField("README.txt", default=False)
    readme_html = models.BooleanField("README.html", default=False)
    readme_pdf = models.BooleanField("README.pdf", default=False)
    added = models.DateTimeField("Added", default=django.utils.timezone.now)
    slug = models.SlugField(null=False, unique=True)
    screens = models.IntegerField("Screenshots", default=0)
    blurb = models.TextField("Blurb", blank=True)
    virtual_machine = models.ForeignKey(VirtualMachine, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to=Q(disk__exact=''))
    WIDTHS = [(640, 'width640'), (800, 'width800'), (1024, 'width1024')]
    HEIGHTS = [(480, 'height480'), (600, 'height600'), (768, 'height768')]
    virtual_machine_width = models.IntegerField(choices=WIDTHS, default=640)
    virtual_machine_height = models.IntegerField(choices=HEIGHTS, default=480)
    def __str__(self): return self.game
    def get_absolute_url(self): return reverse("demos:demo", kwargs={ "slug": self.slug })
    def get_sorted_sources(self): return self.source_set.all().order_by('description')
    def get_file_size(self): return self.getsize(self.filename)
    def get_alt_file_size(self): return self.getsize(self.filename_68k)
    def get_dl3_file_size(self): return self.getsize(self.filename_3)
    def getsize(self, filename):
        try:
            head = self.s3.head_object(
                Bucket = "download.classicmacdemos.com",
                Key = filename
            )
            return convert_size(head["ContentLength"])
        except:
            return 0

class Magazine(models.Model):
    magazine = models.CharField("Magazine", max_length=200)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    url = models.URLField("Webpage", blank=True)
    slug = models.SlugField(null=False, unique=True)
    blurb = models.TextField("Blurb", blank=True)
    image = models.BooleanField("Has image?", default=False)
    def __str__(self): return self.magazine
    def begin(self): return self.source_set.aggregate(Min("year"))
    def end(self): return self.source_set.aggregate(Max("year"))
    def gamecount(self): return self.source_set.aggregate(Count("game"))
    def get_absolute_url(self): return reverse("demos:magazine", kwargs={ "slug": self.slug })
    def unique_game_count(self):
        games = dict()
        for disc in self.source_set.all():
            for game in disc.game.all():
                games[game] = True
        return len(games)

class Source(models.Model):
    game = models.ManyToManyField(Game, blank=True)
    magazine = models.ForeignKey(Magazine, null=True, on_delete=models.SET_NULL)
    description = models.CharField("Description", max_length=200)
    contributor = models.CharField("Contributed by", max_length=200, blank=True)
    contributor_url = models.URLField("Contributor URL", blank=True)
    url = models.URLField("Webpage", blank=True)
    discmaster = models.URLField("DiscMaster URL", blank=True)
    magazine_url = models.URLField("Magazine URL", blank=True)
    magazine_embed_url = models.URLField("Embeddable Magazine URL", blank=True)
    infinite_mac_url = models.URLField("ISO/DMG URL", max_length=500, blank=True)
    virtual_machine = models.ForeignKey(VirtualMachine, related_name="source_virtual_machine", on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to=~Q(disk__exact=''))
    osx_virtual_machine = models.ForeignKey(VirtualMachine, related_name="source_osx_virtual_machine",on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Mac OS X Virtual machine", limit_choices_to=~Q(disk__exact=''))
    year = models.IntegerField("Year", blank=True, default=2000, null=True)
    month = models.IntegerField("Month", blank=True, choices=Months.choices, default=None, null=True)
    disc = models.IntegerField("Disc #", blank=True, default=None, null=True)
    volume = models.IntegerField("Volume #", blank=True, default=None, null=True)
    issue_number = models.IntegerField("Issue #", blank=True, default=None, null=True)
    issue_name = models.CharField("Issue Name", max_length=200, blank=True)
    images = models.IntegerField("Images", default=0)
    blurb = models.TextField("Blurb", blank=True)
    slug = models.SlugField(null=False, unique=True)
    disc2_url = models.URLField("Disc 2 Webpage", blank=True)
    disc2_discmaster = models.URLField("Disc 2 DiscMaster URL", blank=True)
    disc2_infinite_mac_url = models.URLField("Disc 2 ISO/DMG URL", max_length=500, blank=True)
    disc3_url = models.URLField("Disc 3 Webpage", blank=True)
    disc3_discmaster = models.URLField("Disc 3 DiscMaster URL", blank=True)
    disc3_infinite_mac_url = models.URLField("Disc 3 ISO/DMG URL", max_length=500, blank=True)
    disc4_url = models.URLField("Disc 4 Webpage", blank=True)
    disc4_discmaster = models.URLField("Disc 4 DiscMaster URL", blank=True)
    disc4_infinite_mac_url = models.URLField("Disc 4 ISO/DMG URL", max_length=500, blank=True)
    added = models.DateTimeField("Added", default=django.utils.timezone.now)
    def __str__(self): return self.description
    def get_absolute_url(self): return reverse("demos:source", kwargs={ "slug": self.slug })
    def get_sorted_games(self): return self.game.all().order_by('slug')
    def playable_games(self): return self.game.filter(virtual_machine__isnull=False)
    class Meta:
        ordering = ['magazine','year', 'month', 'volume', 'issue_number', 'disc']

class Download(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, auto_created=True)
    downloads = models.IntegerField(default=0, blank=True)
    def __str__(self): return "{game} ({downloads})".format(game=self.game.game, downloads=self.downloads)

class Play(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, auto_created=True)
    plays = models.IntegerField(default=0, blank=True)
    def __str__(self): return "{game} ({plays})".format(game=self.game.game, plays=self.plays)

class Explore(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE, auto_created=True)
    explores = models.IntegerField(default=0, blank=True)
    def __str__(self): return "{source} ({explores})".format(source=self.source.description, explores=self.explores)

class Website(models.Model):
    game      = models.ForeignKey(Game, on_delete=models.CASCADE)
    wikipedia = models.URLField("Wikipedia", blank=True)
    website   = models.URLField("Website", blank=True)
    mobygames = models.URLField("MobyGames", blank=True)
    steam     = models.URLField("Steam", blank=True)
    gog       = models.URLField("GOG", blank=True)
    macintosh_repository = models.URLField("Macintosh Repository", blank=True)
    macintosh_garden     = models.URLField("Macintosh Garden", blank=True)
    wayback_machine      = models.URLField("Wayback Machine", blank=True)
    github               = models.URLField("GitHub", blank=True)
    mac_source_ports     = models.URLField("Mac Source Ports", blank=True)
    def __str__(self): return self.game.game

website/demos/templates/demos/base.html
<!DOCTYPE html>
{% load static %}
{% if not view.kwargs.nonav %}
<html lang="en">
<head>
    <title>{% block title %}Classic Macintosh Game Demos{% endblock %}</title>
    <link rel="stylesheet" href="/classicmacdemos.css" />{% if canonical_uri %}
    <link rel="canonical" href="{{ canonical_uri }}" />{% endif %}{% if not request.session.is_old_browser %}
    <link rel="preconnect" href="{{ request.scheme }}://static.classicmacdemos.com" crossorigin>
    <link rel="icon" href="{{ request.scheme }}:{% static 'icons/hqx.png' %}" />
    <link rel="apple-touch-icon" href="{% static 'icons/hqx.png' %}" />
    <link href="{{ request.scheme }}:{% static 'fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{{ request.scheme }}:{% static 'fontawesome/css/solid.min.css' %}" rel="stylesheet">
    <link rel="alternate" type="application/rss+xml" title="New additions: Classic Macintosh Game Demos" href="{% url 'demos:rss' %}" />
    <meta property="og:title" content="{% block og-title %}Classic Macintosh Game Demos{% endblock %}">
    <meta name="twitter:title" content="{% block tw-title %}Classic Macintosh Game Demos{% endblock %}">
    <meta name="description" content="{% block description %}A collection of game demos for vintage Macintosh computers with operating systems through Mac OS 9, especially games from the mid-1990s and early 2000s.{% endblock %}">
    <meta property="og:description" content="{% block og-description %}A collection of game demos for vintage Macintosh computers with operating systems through Mac OS 9, especially games from the mid-1990s and early 2000s.{% endblock %}">
    <meta name="twitter:description" content="{% block tw-description %}A collection of game demos for vintage Macintosh computers with operating systems through Mac OS 9, especially games from the mid-1990s and early 2000s.{% endblock %}">
    <meta property="og:image" content="{% block og-image %}{{ request.scheme }}:{% static 'icons/splash.png' %}{% endblock %}">
    <meta name="twitter:image" content="{% block tw-image %}{{ request.scheme }}:{% static 'icons/splash.png' %}{% endblock %}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="twitter:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="classicmacdemos.com">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        function change_nav(checkboxElem) {
         var a = document.createElement('a');
         a.target="htmz";
         if (checkboxElem.checked) {
          a.href="{% url 'demos:sources_nn' %}#tab-panel";
          window.history.pushState({}, '', '{% url "demos:sources" %}')
        } else {
          a.href="{% url 'demos:games_nn' %}#tab-panel";
          window.history.pushState({}, '', '{% url "demos:games" %}')
         }
         a.click();
        }
    </script>
    {% block splide %}{% endblock %}{% endif %}
</head>
<body>
    {% if request.session.is_old_browser %}<h1><a href="{% url 'demos:home' %}">Classic Macintosh Game Demos</a></h1>{% else %}
    <iframe hidden name=htmz onload="setTimeout(()=>document.querySelector(contentWindow.location.hash||null)?.replaceWith(...contentDocument.body.childNodes))"></iframe>
    <header><nav><div class="navbar">
        <a href="{% url 'demos:home' %}"><img alt="Classic Macintosh Game Demos" src="{{ request.scheme }}:{% static 'icons/hqx.png' %}" height="32" width="32" title="Home"></a>
        <div class="sitename"><a href="{% url 'demos:home' %}">Classic Macintosh<br>Game Demos</a></div>
        <div class="the-control">
            <div class="button">
             <input type="checkbox" class="checkbox" onchange="change_nav(this);" {% if tab == "discs" %}checked {% endif %}/>
             <div class="slider">
              <span>Games</span>
             </div>
             <div class="background"></div>
            </div>
           </div>           
           <div>
            <a rel="me" href="https://oldbytes.space/@classicmacdemos" title="Follow this site on Mastodon"><img src="{{ request.scheme }}:{% static 'icons/mastodon.png' %}" height="21" width="20" alt="Follow this site on Mastodon"></a>
            <a href="{% url 'demos:rss' %}" title="RSS"><img src="{{ request.scheme }}:{% static 'icons/rss.png' %}" height="20" width="20" alt="RSS"></a>
        </div>
    </div></nav></header>
    {% endif %}
{% endif %}
<div id="tab-panel" role="tabpanel">
<main>
<header>{% block header %}{% endblock %}</header>
{% block content %}{% endblock %}
</main>
<footer><section><p>{% block footer %}{% endblock %} <a href="{% url 'demos:about' %}">About this website</a></p></section></footer>
</div>
{% if not view.kwargs.nonav %}
</body>
</html>
{% endif %}

website/demos/templates/demos/game_cards.html
{% load static %}
{% if border %}<aside style="text-align: center; {% if clear %}border: none;{% endif %}">{% endif %}
{% if games.count > 0 %}
{% if header %}<h3>{{ header }}</h3>{% endif %}
<div style="text-align: center;">
    {% for game in games %}
    {% if request.session.is_old_browser %}
        <br>
        <table width="100%"><tr>
            <td width="32"><a href="{% url 'demos:demo' game.slug %}"><img src="{{ request.scheme }}:{% static 'demos/'%}{{game.slug}}/icon.png" height="32" width="32" alt="{{ game.game }}"></a></td>
        <td align="left" width="100%"><a href="{% url 'demos:demo' game.slug %}">{{ game.game }}</a><br>{{ game.year }}</td>
    </tr></table>
    {% else %}
    <div class="game-card"><a href="{% url 'demos:demo' game.slug %}"><div style="text-align: left;">
        <img src="{{ request.scheme }}:{% static 'demos/'%}{{game.slug}}/icon.png" height="32" width="32" alt="{{ game.game }}">
    <div style="float:inline-start; display:box; width: 190px;">
        <span class="text">{{ game.game }}<br /></span>
        <span class="icons">{% if game.virtual_machine %}<span aria-hidden="true" class="fa-solid fa-play" title="Play"></span><span class="fa-sr-only">Play</span>{% endif %}</span>
        <span class="text">{{ game.year }}</span>
    </div>
    </div></a></div>
    {% endif %}
    {% endfor %}
</div>{% endif %}
{% if border %}</aside>{% endif %}

website/demos/templates/demos/game_list.html
{% extends "demos/base.html" %}
{% load static %}
{% block title %}{% block og-title %}{% block tw-title %}Games | Classic Macintosh Game Demos{% endblock %}{% endblock %}{% endblock %}
{% block content %}
<section>{% include "demos/game_cards.html" with games=game_list %}</section>
{% endblock %}

website/demos/templates/demos/home.html
{% extends "demos/base.html" %}
{% load markdown_extras %}
{% load static %}
{% block content %}
<section>
{% if not request.session.is_old_browser %}
<aside>
<h3>Play retro Macintosh games in your browser</h3>
<div class="homebutton"><a href="{% url 'demos:playable' %}"><b><span aria-hidden="true" class="fa-solid fa-play"></span> Play the games &rarr;</b></a></div>
<p>Play <b>{{ infinitemac.count }}</b> demos for Classic-era Macintosh videogames in your browser right now, courtesy of <a href="https://infinitemac.org/">Infinite Mac</a>. Flash back to legendary Mac exclusives like <a href="{% url 'demos:demo' 'glider-pro' %}">Glider Pro</a>, <a href="{% url 'demos:demo' 'spaceward-ho' %}">Spaceward Ho!</a>, and the <a href="{% url 'demos:demo' 'marathon-1' %}">whole</a> <a href="{% url 'demos:demo' 'marathon-2-durandal' %}">Marathon</a> <a href="{% url 'demos:demo' 'marathon-infinity' %}">trilogy</a>.</p>
<p><b>Most played games:</b></p>
{% include "demos/game_cards.html" with games=infinitemac|slice:":5" tiny=True %}
</aside>
{% endif %}  
<aside>
<h3>Download retro Macintosh game demos</h3>
<div class="homebutton"><a href="{% url 'demos:games' %}"><b><span aria-hidden="true" class="fa-solid fa-download" title="Download"></span> Get the games{% if not request.session.is_old_browser %} &rarr;{% endif %}</b></a></div>
<p>Download <b>{{ downloads.count }}</b> game demos to your Classic-era Macintoshes or emulators for a quick retrogaming fix. Vintage browser users, try the site's <a href="http://classicmacdemos.com/">http mode</a>.</p>
<p><b>Most downloaded games:</b></p>
{% include "demos/game_cards.html" with games=downloads|slice:":5" tiny=True %}
</aside>  
<aside>
<h3>Browse Macintosh magazine cover CDs</h3>
<div class="homebutton"><a href="{% url 'demos:sources' %}"><b><span aria-hidden="true" class="fa-solid fa-compact-disc" title="Discs"></span> Explore the CDs{% if not request.session.is_old_browser %} &rarr;{% endif %}</b></a></div>
<p>Relive the retro computer magazine experience with a library of <b>{{ sources }}</b> cover CDs from Macintosh computer magazines, all explorable in a live <a href="https://infinitemac.org/">Infinite Mac</a> virtual machine.</p> 
<p>Includes CDs that originally came bundled with <a href="{% url 'demos:magazine' 'macworld' %}">Macworld</a>, <a href="{% url 'demos:magazine' 'macaddict' %}">Macaddict</a>, and <a href="{% url 'demos:magazine' 'inside-mac-games' %}">Inside Mac Games</a>, plus a growing collection of global magazines.</p>
{% for disc in discs|slice:":1" %}
<p><b>Newest CD:</b></p>
<a href="{% url 'demos:source' disc.slug %}"><img src="{{ request.scheme }}:{% static 'discs' %}/{{ disc.slug }}/image-1.png" alt="{{ disc.description }}"></a>
{% endfor %}
</aside>
</section>
{% endblock %}

website/demos/templates/demos/magazine_detail.html
{% extends "demos/base.html" %}
{% load markdown_extras %}
{% load static %}
{% block title %}{% block og-title %}{% block tw-title %}{{ magazine }}  ({{ magazine.begin.year__min }}{% if magazine.source_set.count > 1 and magazine.end.year__max > magazine.begin.year__min %} - {{ magazine.end.year__max }}{% endif %}) | Classic Macintosh Game Demos{% endblock %}{% endblock %}{% endblock %}
{% block description %}{% block og-description %}{% block tw-description %}Download and browse {{ magazine.source_set.all.count }} discs from {{ magazine }} ({{ magazine.begin.year__min }}{% if magazine.source_set.count > 1 and magazine.end.year__max > magazine.begin.year__min %} - {{ magazine.end.year__max }}{% endif %}) | Classic Macintosh Game Demos{% endblock %}{% endblock %}{% endblock %}
{% block og-image %}{% block tw-image %}{% if magazine.image %}{{ request.scheme }}:{% static 'magazines'%}/{{ magazine.slug }}/image-1.png{% else %}{{ block.super }}{% endif %}{% endblock %}{% endblock %}
{% block header %}
<h1>{{ magazine }}</h1>
<section>
<a href="{% url 'demos:sources' %}"><b>{% if not request.session.is_old_browser %}&larr; {% endif %}All magazines</b></a>
{% if request.session.is_old_browser %}<p>{% endif %}
{% if magazine.url %}<a href="{{ magazine.url }}" target="_blank"><b><span aria-hidden="true" class="fa-solid fa-globe"></span> Website</b></a>{% endif %}
{% if request.session.is_old_browser %}</p>{% endif %}
</section>
{% endblock %}
{% block content %}
<section>
{% if magazine.blurb %}<article>{{ magazine.blurb | markdown | safe }}</article>{% endif %}
<section>
    {% for source in magazine.source_set.all %}
    <aside class="magazine-card"><a href="{% url 'demos:source' source.slug %}">
    <strong>{{ source }}</strong>
    {% if source.month or source.year %}<div><span aria-hidden="true" class="fa-solid fa-calendar" title="Released"></span><span class="fa-sr-only">Released</span> {% if source.month %}{{ source.get_month_display }} {% endif %}{% if source.year %}{{ source.year }}{% endif %}</div>{% endif %}
    <div class="icons">
    {% if source.url %}<span aria-hidden="true" class="fa-solid fa-compact-disc" title="CD"></span><span class="fa-sr-only">CD</span>{% endif %}
    {% if source.disc2_url or source.disc2_infinite_mac_url %}<span aria-hidden="true" class="fa-solid fa-compact-disc" title="CD"></span><span class="fa-sr-only">CD 2</span>{% endif %}
    {% if source.disc3_url or source.disc3_infinite_mac_url %}<span aria-hidden="true" class="fa-solid fa-compact-disc" title="CD"></span><span class="fa-sr-only">CD 3</span>{% endif %}
    {% if source.disc4_url or source.disc4_infinite_mac_url %}<span aria-hidden="true" class="fa-solid fa-compact-disc" title="CD"></span><span class="fa-sr-only">CD 4</span>{% endif %}
    {% if source.url %} | {% endif %} 
    {% if source.magazine_url or source.magazine_embed_url %}<span aria-hidden="true" class="fa-solid fa-book-open" title="Read"></span><span class="fa-sr-only">Read</span> | {% endif %}
    <span aria-hidden="true" class="fa-solid fa-download" title="Demos"></span><span class="fa-sr-only">Demos</span> {{ source.game.all.count }} | 
    <span aria-hidden="true" class="fa-solid fa-play" title="Playable demos"></span><span class="fa-sr-only">Play</span> {{ source.playable_games.count }}
    </div>
    {% if not request.session.is_old_browser %}{% if source.images >= 1 %}<img src="{{ request.scheme }}:{% static 'discs' %}/{{ source.slug }}/image-1.png" alt="{{ source.description }}">{% else %}<img src="{{ request.scheme }}:{% static 'icons' %}/cd-medium.png" alt="{{ source.description }}">{% endif %}{% endif %}
    </a></aside>
    {% if request.session.is_old_browser %}<p>{% endif %}
    {% endfor %}
    </section>
</section>
{% endblock %}

website/demos/templates/demos/splide.html
{% load static %}{% if not request.session.is_old_browser %}<script src="{{ request.scheme }}:{% static 'splide/splide.min.js' %}"></script>
    <link rel="stylesheet" href="{{ request.scheme }}:{% static 'splide/splide.min.css' %}">{% endif %}